metadata:
  name: fraud-detection
proxy: nil
image:
  name: intel/ai-workflows
dataset:
  type: <nfs/s3/local>
  local:
    dataset_path: nil
    preprocess_path: nil
    gnn_path: nil
    user_config_path: nil
  nfs:
    server: nil
    path: nil
    subPath: nil
    user_config_path: nil
  s3:
    key: nil
    config_key: nil
